logging:
  level:
    org.springframework: error
    org.springframework.security: debug


jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/th_auth?useUnicode=true&characterEncoding=UTF8&useSSL=false
  user: auth_app
  pass: auth_app

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
